# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

version = 1

[[annotations]]
path = [".vscode/*", "README.md"]
SPDX-FileCopyrightText = "2024 Samuel Wu"
SPDX-License-Identifier = "0BSD"
